import json
import numpy as np

# Let's inspect the metrics JSON generated by evaluate_validation.py
with open("Data/outputs/metrics/v2_validation_baseline.json", "r") as f:
    data = json.load(f)

print(f"Number of samples (Validation Set): 365 days * 4 cycles * 33x25 grid ~ Millions of grid points, but technically 1460 slices")
print(f"Metrics (Global Threshold):")
for lead, metrics in data["global_threshold"].items():
    print(f"{lead}: CSI={metrics['CSI']:.4f}, POD={metrics['POD']:.4f}, FAR={metrics['FAR']:.4f}, Brier={metrics['Brier']:.4f}, ECE={metrics['ECE']:.4f}, PR-AUC={metrics['PR_AUC']:.4f}")

